# Generated by Django 3.2 on 2021-05-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='phone',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
