# Generated by Django 3.2 on 2021-05-24 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_commentmodel_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='post',
        ),
    ]
