# Generated by Django 3.2 on 2021-05-24 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_commentmodel_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='posts.postmodel'),
            preserve_default=False,
        ),
    ]
