# Generated by Django 3.2 on 2021-05-25 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_commentmodel_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='body',
            new_name='comment',
        ),
    ]
