# Generated by Django 3.2 on 2021-05-25 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_rename_body_commentmodel_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='approved_comment',
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='comment',
            field=models.TextField(verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_on'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='name',
            field=models.CharField(max_length=80, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.postmodel', verbose_name='post'),
        ),
    ]
