# Generated by Django 3.2 on 2021-06-01 04:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilModel',
            new_name='ProfileModel',
        ),
    ]
