# Generated by Django 3.2 on 2021-05-27 05:15

from django.db import migrations, models
import pages.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_partnermodel_teammodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammodel',
            name='image',
            field=models.ImageField(upload_to='team', validators=[pages.validators.clean_picture], verbose_name='image'),
        ),
    ]
