# Generated by Django 3.2 on 2021-05-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
