# Generated by Django 3.2 on 2021-05-23 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210523_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='color',
            new_name='colors',
        ),
    ]
